// tanstack-stack/app/components/Compose.tsx
import { useForm } from '@tanstack/react-form';
import { useMutation, useQueryClient } from '@tanstack/react-query';
import { useServerFn } from '@tanstack/react-start';
import { feedQueryOptions } from '~/lib/queries';
import { POST_MAX_LENGTH, postCreateSchema } from '~/lib/schemas';
import { createPostFn } from '~/lib/server';

export default function Compose() {
  const queryClient = useQueryClient();
  const createPost = useServerFn(createPostFn);

  const createPostMutation = useMutation({
    mutationFn: (content: string) => createPost({ data: { content } }),
    onSuccess: () => queryClient.invalidateQueries({ queryKey: feedQueryOptions.queryKey }),
  });

  const form = useForm({
    defaultValues: { content: '' },
    // Standard Schema: TanStack Form v1 accepts Zod schemas directly
    validators: { onChange: postCreateSchema },
    onSubmit: async ({ value, formApi }) => {
      await createPostMutation.mutateAsync(value.content);
      formApi.reset();
    },
  });

  return (
    <div className="rounded-lg border bg-white p-4">
      <form
        onSubmit={(e) => {
          e.preventDefault();
          e.stopPropagation();
          void form.handleSubmit();
        }}
      >
        <form.Field name="content">
          {(field) => (
            <textarea
              value={field.state.value}
              onChange={(e) => field.handleChange(e.target.value)}
              onBlur={field.handleBlur}
              placeholder="What's happening?"
              aria-label="Post content"
              className="w-full resize-none rounded border p-3 focus:ring-2 focus:ring-blue-500 focus:outline-none"
              rows={3}
            />
          )}
        </form.Field>

        <div className="mt-2 flex items-center justify-between">
          <form.Subscribe selector={(state) => state.values.content.trim().length}>
            {(charCount) => (
              <span
                className={`text-sm ${charCount > POST_MAX_LENGTH ? 'text-red-500' : 'text-gray-500'}`}
              >
                {charCount}/{POST_MAX_LENGTH}
              </span>
            )}
          </form.Subscribe>

          <form.Subscribe
            selector={(state) => [state.canSubmit, state.isSubmitting, state.values.content] as const}
          >
            {([canSubmit, isSubmitting, content]) => (
              <button
                type="submit"
                disabled={!canSubmit || isSubmitting || content.trim().length === 0}
                className="rounded-full bg-blue-500 px-6 py-2 text-white hover:bg-blue-600 disabled:cursor-not-allowed disabled:opacity-50"
              >
                {isSubmitting ? 'Posting...' : 'Post'}
              </button>
            )}
          </form.Subscribe>
        </div>

        {createPostMutation.error && (
          <p className="mt-2 text-sm text-red-500">{createPostMutation.error.message}</p>
        )}
      </form>
    </div>
  );
}

// astro-stack/src/components/Compose.svelte
<!--
  Compose island: creates a post via an Astro Action, then refreshes the feed.
-->
<script lang="ts">
  import { actions } from 'astro:actions';
  import { createMutation, useQueryClient } from '@tanstack/svelte-query';
  import { FEED_KEY } from '@/lib/feedCache';
  import { POST_MAX_LENGTH } from '@/lib/schemas';

  const queryClient = useQueryClient();

  let content = $state('');
  const charCount = $derived(content.trim().length);
  const isValid = $derived(charCount > 0 && charCount <= POST_MAX_LENGTH);

  const createPost = createMutation(() => ({
    mutationFn: (text: string) => actions.createPost.orThrow({ content: text }),
    onSuccess: () => {
      content = '';
      return queryClient.invalidateQueries({ queryKey: FEED_KEY });
    },
  }));

  function handleSubmit(event: SubmitEvent) {
    event.preventDefault();
    if (isValid && !createPost.isPending) createPost.mutate(content);
  }
</script>

<div class="rounded-lg border bg-white p-4">
  <form onsubmit={handleSubmit}>
    <textarea
      bind:value={content}
      placeholder="What's happening?"
      aria-label="Post content"
      class="w-full resize-none rounded border p-3 focus:ring-2 focus:ring-blue-500 focus:outline-none"
      rows="3"
    ></textarea>
    <div class="mt-2 flex items-center justify-between">
      <span class={['text-sm', charCount > POST_MAX_LENGTH ? 'text-red-500' : 'text-gray-500']}>
        {charCount}/{POST_MAX_LENGTH}
      </span>
      <button
        type="submit"
        disabled={!isValid || createPost.isPending}
        class="rounded-full bg-blue-500 px-6 py-2 text-white hover:bg-blue-600 disabled:cursor-not-allowed disabled:opacity-50"
      >
        {createPost.isPending ? 'Posting...' : 'Post'}
      </button>
    </div>
    {#if createPost.isError}
      <p class="mt-2 text-sm text-red-500">{createPost.error?.message}</p>
    {/if}
  </form>
</div>
